name: cla-check
on: [pull_request_target]

jobs:
  cla-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if CLA signed
        uses: ./
        env:
          SIGNED_CLA_JSON: ${{ secrets.SIGNED_CLA_JSON }}
